import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "./Com/Header";
import Footer from "./Com/Footer";
import 'bootstrap/dist/css/bootstrap.min.css';

const roboto = Roboto({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: "Amrit project1",
  description: "Generated by Amrit kandel",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
   <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
